const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.AJAX,
		C3.Plugins.Browser,
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.SubVar
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{Audio: 0},
	{AJAX: 0},
	{Browser: 0},
	{btnMulai: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Text: 0},
	{textPengantar: 0},
	{btnAngka: 0},
	{btnHuruf: 0},
	{mulaiAngka: 0},
	{mulaiHuruf: 0},
	{Text2: 0},
	{Text3: 0},
	{Text4: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{NamaSuara: 0},
	{spr_Huruf: 0},
	{back: 0},
	{next: 0},
	{spr_Angka: 0},
	{spr_gambarsoalAngka: 0},
	{judulkuis: 0},
	{apakahBenar: 0},
	{sudahDiklik: 0},
	{spr_jawabansoalAngka: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{hati1: 0},
	{hati2: 0},
	{hati3: 0},
	{spr_nyawa: 0},
	{Text5: 0},
	{Nyawa_kuis: 0},
	{TotalBenar: 0},
	{PilihanMenu: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	btnMulai: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	textPengantar: class extends self.ITextInstance {},
	btnAngka: class extends self.ITextInstance {},
	btnHuruf: class extends self.ITextInstance {},
	mulaiAngka: class extends self.ISpriteInstance {},
	mulaiHuruf: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	spr_Huruf: class extends self.ISpriteInstance {},
	back: class extends self.ISpriteInstance {},
	next: class extends self.ISpriteInstance {},
	spr_Angka: class extends self.ISpriteInstance {},
	spr_gambarsoalAngka: class extends self.ISpriteInstance {},
	judulkuis: class extends self.ITextInstance {},
	spr_jawabansoalAngka: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	hati1: class extends self.ISpriteInstance {},
	hati2: class extends self.ISpriteInstance {},
	hati3: class extends self.ISpriteInstance {},
	spr_nyawa: class extends self.ISpriteInstance {},
	Text5: class extends self.ITextInstance {}
}